$table->decimal('current_valution', 40, 2)->default(0);
$table->decimal('floor', 40, 2)->default(0);
$table->decimal('cap', 40, 2)->default(0);
$table->decimal('fund_required', 40, 2)->default(0);
$table->text('details_of_previous_fund_round')->nullable();
$table->decimal('paidup_capital', 40, 2)->default(0);
$table->decimal('authorised_capital', 40, 2)->default(0);
$table->decimal('proposed_of_equity_dilusion', 40, 2)->default(0);
$table->decimal('per_share_price', 40, 2)->default(0);
$table->decimal('equity_offered', 40, 2)->default(0);
$table->decimal('face_value', 40, 2)->default(0);
$table->bigInteger('minimum_shares_to_invest');
$table->text('pitch_video')->nullable();
$table->text('pitch_deck_file')->nullable();
$table->text('finacial_projection')->nullable();
$table->text('dd_report')->nullable();
$table->text('shuruup_research_report')->nullable();
$table->text('valuation_report_file')->nullable();
$table->text('digio_ssa_id')->nullable();
$table->text('digio_ssa_coordinates')->nullable();
$table->text('digio_sha_id')->nullable();
$table->text('digio_sha_coordinates')->nullable();
$table->enum('status', ['pending', 'coming soon', 'Private Limited', 'raising now', 'private deal room', 'event', 'completed'])->nullable()->comment('0 pending, 1 coming soon, 2 raising now, 3 private deal room, 4 event, 5 completed');